export const cars = [
  {
    name: "Avanza",
    price: 600000,
    description: "Mobil Dengan Supir + Bensin Rp.600.000 / Day",
    duration: "13 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 6,
    transmission: "Matic / Manual",
    notes: "Harga Sewa Tidak Termasuk Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/avanza.webp",
  },
  {
    name: "New Avanza",
    price: 700000,
    description: "Mobil Dengan Supir + Bensin Rp.700.000 / Day",
    duration: "15 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 6,
    transmission: "Matic / Manual",
    notes: "Harga Sewa Tidak Termasuk Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/new-avanza.webp",
  },
  {
    name: "Innova Reborn",
    price: 850000,
    description: "Mobil Dengan Supir + Bensin Rp. 850.000 / Day",
    duration: "15 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 6,
    transmission: "Matic / Manual",
    notes: "Harga Sewa Tidak Termasuk Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/innova-reborn.webp",
  },
  {
    name: "Innova Venturer",
    price: 1100000,
    description: "Mobil Dengan Supir + Bensin Rp. 1.100.000 / Day",
    duration: "15 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 6,
    transmission: "Matic / Manual",
    notes: "Harga Sewa Tidak Termasuk Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/venturer.webp",
  },
  {
    name: "Innova Zenix G",
    price: 1100000,
    description: "Mobil Dengan Supir + Bensin Rp. 1.100.000 / Day",
    duration: "15 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 6,
    transmission: "Matic",
    notes: "Harga Sewa Tidak Termasuk Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/innova-zenix-g.webp",
  },
  {
    name: "Innova Zenix Q",
    price: 1500000,
    description: "Mobil Dengan Supir + Bensin Rp. 1.500.000 / Day",
    duration: "15 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 5,
    transmission: "Matic",
    notes: "Harga Sewa Tidak Termasuk Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/innova-zenix-q.webp",
  },
  {
    name: "Hiace Luxury",
    price: 2000000,
    description: "Mobil Dengan Supir + Bensin Rp. 2.000.000 / Day",
    duration: "15 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 8,
    transmission: "Matic",
    notes: "Harga Sewa Tidak Termasuk Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/hiace-luxury.webp",
  },
  {
    name: "Alphard Facelift",
    price: 2800000,
    description: "Mobil Dengan Supir + Bensin Rp. 2.800.000 / Day",
    duration: "15 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 5,
    transmission: "Matic",
    notes: "Harga Sewa Tidak Termasuk Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/alphard-facelift.webp",
  },
  {
    name: "Bis Bus",
    price: 3000000,
    description: "Mobil Dengan Supir + Bensin Rp. 3.000.000 / Day",
    duration: "15 Jam",
    maxTime: "22.00",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 50,
    transmission: "",
    notes:
      "Harga Sewa Tidak Termasuk Fee Crew, Tol, Parkir, Tiket Masuk Tempat Wisata",
    image: "/armada/bis-bus.webp",
  },
  {
    name: "Alphard Hybrid",
    price: 3500000,
    description: "Mobil Dengan Supir + Bensin Rp. 3.500.000 / Day",
    duration: "15 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 5,
    transmission: "Matic",
    notes: "Harga Sewa Tidak Termasuk Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/alphard-hybrid.webp",
  },
  {
    name: "Hiace Premio",
    price: 1500000,
    description: "Mobil Dengan Supir + Bensin Rp. 1.500.000 / Day",
    duration: "15 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 14,
    transmission: "Matic / Manual",
    notes: "Harga Sewa Tidak Termasuk Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/hiace-luxury.webp",
  },
  {
    name: "Pajero",
    price: 1500000,
    description: "Mobil Dengan Supir + Bensin Rp. 1.500.000 / Day",
    duration: "15 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 6,
    transmission: "Matic / Manual",
    notes: "Harga Sewa Tidak Termasuk Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/pajero.webp",
  },
  {
    name: "Fortuner",
    price: 1500000,
    description: "Mobil Dengan Supir + Bensin Rp. 1.500.000 / Day",
    duration: "15 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 6,
    transmission: "Matic / Manual",
    notes: "Harga Sewa Tidak Termasuk Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/fortuner.webp",
  },
  {
    name: "Alphard Transformers",
    price: 2500000,
    description: "Mobil Dengan Supir + Bensin Rp. 2.500.000 / Day",
    duration: "15 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 5,
    transmission: "Matic / Manual",
    notes: "Harga Sewa Tidak Termasuk Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/alphard-transformer.webp",
  },
  {
    name: "Bus 35 Seat",
    price: 2500000,
    description: "Mobil Dengan Supir + Bensin Rp. 2.500.000 / Day",
    duration: "15 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 35,
    transmission: "Matic / Manual",
    notes:
      "Harga Sewa Tidak Termasuk Fee Crew, Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/bis-bus.webp",
  },
  {
    name: "Hiace Commuter",
    price: 1200000,
    description: "Mobil Dengan Supir + Bensin Rp. 1.200.000 / Day",
    duration: "15 Jam",
    maxTime: "22.30",
    overtime: "10% Dari Tarif Per Jam",
    capacity: 16,
    transmission: "Matic / Manual",
    notes: "Harga Sewa Tidak Termasuk Parkir, Tol, Tiket Masuk Tempat Wisata",
    image: "/armada/hiace-commuter.webp",
  },
];
