
export const oneDayPackages = [
  {
    name: "Paket Merapi",
    duration: "1 Hari",
    location: "Yogyakarta",
    destinations: [
      "Pasar Ngasem",
      "Tamansari",
      "Lava Tour",
      "Heha Sky View",
      "Pusat Oleh-oleh",
    ],
    price: "308.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Patehan",
    duration: "1 Hari",
    location: "Yogyakarta",
    destinations: [
      "Pasar Ngasem",
      "Taman Sari",
      "Hutan Pinus",
      "Pictniq",
      "Pusat Oleh Oleh",
    ],
    price: "218.000",
    image: "https://images.unsplash.com/photo-1559126137-3485b7427625?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Bantul",
    duration: "1 Hari",
    location: "Yogyakarta",
    destinations: [
      "Kebun Buah Mangunan",
      "Hutan Pinus Mangunan",
      "Pantai Mesra",
      "Heha Ocean",
      "Pusat Oleh-oleh",
    ],
    price: "239.000",
    image: "https://images.unsplash.com/photo-1570162872928-08f6756a402c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Borobudur",
    duration: "1 Hari",
    location: "Yogyakarta",
    destinations: [
      "Candi Borobudur",
      "VW Safari",
      "Studio Gamplong",
      "Mahaloka Paradise",
      "Pusat Oleh-oleh",
    ],
    price: "349.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Prambanan",
    duration: "1 Hari",
    location: "Yogyakarta",
    destinations: [
      "Tebing Breksi",
      "Obelix Hills",
      "Candi Prambanan",
      "Pinus Pengger",
      "Pusat Oleh-oleh",
    ],
    price: "247.000",
    image: "https://images.unsplash.com/photo-1559126137-3485b7427625?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Imogiri",
    duration: "1 Hari",
    location: "Yogyakarta",
    destinations: [
      "Taman Sari",
      "Hutan Pinus",
      "Pantai parangtritis",
      "Obelix Sea View",
      "Pusat Oleh-oleh",
    ],
    price: "228.000",
    image: "https://images.unsplash.com/photo-1570162872928-08f6756a402c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Gunung Kidul",
    duration: "1 Hari",
    location: "Yogyakarta",
    destinations: [
      "Cave Tubing Goa Pindul",
      "Puncak Segoro",
      "Pantai Ngobaran",
      "Malioboro",
      "Pusat Oleh-oleh",
    ],
    price: "258.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Kulon Progo",
    duration: "1 Hari",
    location: "Yogyakarta",
    destinations: [
      "Tumpeng Manoreh",
      "Candi Borobudur",
      "Air Terjun Kedung Kayang",
      "Obelix Village",
      "Wisata Oleh Oleh",
    ],
    price: "288.000",
    image: "https://images.unsplash.com/photo-1559126137-3485b7427625?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];

export const twoDayPackages = [
  {
    name: "Paket Sewon",
    duration: "2 Hari",
    location: "Yogyakarta",
    destinations: [
      "Pasar Ngasem",
      "Tamansari",
      "Candi Prambanan",
      "Kebun Buah Mangunan",
      "Hutan Pinus",
      "Pantai Parangtritis",
      "Obellix Sea View",
      "Pusat Oleh-oleh",
    ],
    price: "747.000",
    image: "https://images.unsplash.com/photo-1570162872928-08f6756a402c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Gondomanan",
    duration: "2 Hari",
    location: "Yogyakarta",
    destinations: [
      "Suraloka Zoo",
      "Bhumi Merapi",
      "Ibarbo Park",
      "Pasar Ngasem",
      "Candi Prambanan",
      "Tempo Gelato",
      "Pusat Oleh-oleh",
    ],
    price: "759.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Wonosari",
    duration: "2 Hari",
    location: "Yogyakarta",
    destinations: [
      "Heha Ocean View",
      "Pantai Watulawang",
      "Pinus Pengger",
      "Pasar Ngasem",
      "Keraton",
      "Tebing Breksi",
      "Candi Plaosan",
      "Pusat Oleh-oleh",
    ],
    price: "709.000",
    image: "https://images.unsplash.com/photo-1559126137-3485b7427625?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Krapyak",
    duration: "2 Hari",
    location: "Yogyakarta",
    destinations: [
      "Pantai Mesra",
      "Pantai Ngobaran",
      "Obelix Sea View",
      "Heha Sky View",
      "Tebing Breksi",
      "Candi Prambanan",
      "Pusat oleh-Oleh",
    ],
    price: "778.000",
    image: "https://images.unsplash.com/photo-1570162872928-08f6756a402c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Kotagede",
    duration: "2 Hari",
    location: "Yogyakarta",
    destinations: [
      "Kebun Buah Mangunan",
      "Hutan Pinus",
      "Gumuk Pasir",
      "Pantai Parangtritis",
      "Obelix Sea View",
      "Pasar Ngasem",
      "Tamansari",
      "Studio Gamplong",
      "Mahaloka Paradise",
      "Pule Payung",
      "Pusat Oleh-oleh",
    ],
    price: "747.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Gamping",
    duration: "2 Hari",
    location: "Yogyakarta",
    destinations: [
      "Taman Sari",
      "Kopi Klothok",
      "Obelix Hills",
      "Tebing Breksi",
      "Malioboro",
      "Tumpeng Menoreh",
      "VW Safari",
      "Borobudur",
      "Pusat Oleh-oleh",
    ],
    price: "879.000",
    image: "https://images.unsplash.com/photo-1559126137-3485b7427625?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Gedongtengen",
    duration: "2 Hari 1 Malam",
    location: "Yogyakarta",
    destinations: [
      "Tumpeng Menoreh",
      "Studio Gamplong",
      "Mahaloka Paradise",
      "Tempo Gelato",
      "Heha Sky View",
      "Pantai Mesra",
      "Pantai Drini",
      "Pusat Oleh-oleh",
    ],
    price: "829.000",
    image: "https://images.unsplash.com/photo-1570162872928-08f6756a402c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Pundong",
    duration: "2 Hari",
    location: "Yogyakarta",
    destinations: [
      "Borobudur",
      "Air Terjun Kedung Kayang",
      "Lava Tour",
      "Kopi Klothok",
      "Goa Pindul",
      "Pantai Ngobaran",
      "Puncak Segoro",
      "Wisata Oleh Oleh",
    ],
    price: "877.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Mantrijeron",
    duration: "2 Hari 1 Malam",
    location: "Yogyakarta",
    destinations: [
      "Pasar Ngasem",
      "Keraton",
      "Pictniq",
      "Malioboro",
      "Hutan Pinus",
      "Tempo Glato",
      "Obelix Hills",
      "Tebing Breksi",
      "Pusat oleh-oleh",
    ],
    price: "699.000",
    image: "https://images.unsplash.com/photo-1559126137-3485b7427625?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];

export const threeDayPackages = [
  {
    name: "Jogokaryan",
    duration: "3 Hari 2 Malam",
    location: "Yogyakarta",
    destinations: [
      "Kopi Klothok",
      "Museum Merapi",
      "Candi Plaosan",
      "Tebing Breksi",
      "Hutan Pinus Asri",
      "Songgo Langit",
      "Pantai Parangtritis",
      "Malioboro",
      "Pasar Ngasem",
      "Tamansari",
      "Studio Gamplong",
      "Pusat Oleh Oleh",
    ],
    price: "1.027.000",
    image: "https://images.unsplash.com/photo-1570162872928-08f6756a402c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Mangkuyudan",
    duration: "3 Hari 2 Malam",
    location: "Yogyakarta",
    destinations: [
      "Cave Tubing Goa Pindul",
      "Pantai Drini",
      "Obelix Sea View",
      "Pule Payung",
      "Sungai Mudal",
      "Studio Gamplong",
      "Malioboro",
      "Pasar Ngasem",
      "Tamansari",
      "Hutan Pinus Asri",
      "Heha SkyView",
      "Wisata Oleh Oleh",
    ],
    price: "1.125.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Kaliurang",
    duration: "3 Hari 2 Malam",
    location: "Yogyakarta",
    destinations: [
      "Candi Prambanan",
      "Tebing Breksi",
      "Obelix Hills",
      "Sunrise Mangunan",
      "Hutan Pinus Asri",
      "Gumuk Pasir",
      "Pantai Parangtritis",
      "Pasar Ngasem",
      "Tamansari",
      "Keraton",
      "Malioboro",
      "Wisata Oleh Oleh",
    ],
    price: "1.125.000",
    image: "https://images.unsplash.com/photo-1559126137-3485b7427625?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Danurejan",
    duration: "3 Hari 2 Malam",
    location: "Yogyakarta",
    destinations: [
      "Kopi klothok",
      "Lava tour",
      "Borobudur",
      "Malioboro",
      "Pantai Indrayanti",
      "Pantai Drini",
      "Heha Sky View",
      "Pinus Pengger",
      "Pasar Ngasem",
      "Tamansari",
      "Jurang Kanigoro",
      "Wisata Oleh Oleh",
    ],
    price: "1.194.000",
    image: "https://images.unsplash.com/photo-1570162872928-08f6756a402c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];

export const companyPackages = [
  {
    name: "Paket Adventure",
    duration: "2 Hari 1 Malam",
    location: "Yogyakarta",
    destinations: [
      "Outbound",
      "Cave Tubing Goa Pindul",
      "Heha Sky View",
      "Gala Dinner",
      "Pantai Parangtritis",
      "Jeep Gumuk Pasir",
      "Obelix Sea View",
      "Pusat Oleh Oleh",
    ],
    price: "1.677.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];
