
export const oneDayPackages = [
  {
    name: "Paket Merapi",
    duration: "1 Hari",
    location: "Yogyakarta",
    short_description: "Jelajahi kegagahan Gunung Merapi dan keindahan sekitarnya dalam satu hari.",
    destinations: [
      "Pasar Ngasem",
      "Tamansari",
      "Lava Tour Merapi",
      "Heha Sky View",
      "Pusat Oleh-oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "308.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    featured: true,
  },
  {
    name: "Paket Patehan",
    duration: "1 Hari",
    location: "Yogyakarta",
    short_description: "Nikmati suasana sejuk hutan pinus dan spot foto unik di Puncak Becici.",
    destinations: [
      "Pasar Ngasem",
      "Taman Sari",
      "Hutan Pinus",
      "Puncak Becici",
      "Pusat Oleh Oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "218.000",
    image: "https://images.unsplash.com/photo-1559126137-3485b7427625?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    featured: true,
  },
  {
    name: "Paket Bantul",
    duration: "1 Hari",
    location: "Yogyakarta",
    short_description: "Jelajahi pesona alam selatan Jogja, dari kebun buah hingga pantai eksotis.",
    destinations: [
      "Kebun Buah Mangunan",
      "Hutan Pinus Mangunan",
      "Pantai Mesra",
      "Heha Ocean",
      "Pusat Oleh-oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "239.000",
    image: "https://images.unsplash.com/photo-1570162872928-08f6756a402c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    featured: true,
  },
  {
    name: "Paket Borobudur",
    duration: "1 Hari",
    location: "Yogyakarta",
    short_description: "Saksikan kemegahan Candi Borobudur dan nikmati petualangan VW Safari.",
    destinations: [
      "Candi Borobudur",
      "VW Safari",
      "Studio Gamplong",
      "Mahaloka Paradise",
      "Pusat Oleh-oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "349.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Prambanan",
    duration: "1 Hari",
    location: "Yogyakarta",
    short_description: "Kunjungi Candi Prambanan yang megah dan nikmati pemandangan dari Obelix Hills.",
    destinations: [
      "Tebing Breksi",
      "Obelix Hills",
      "Candi Prambanan",
      "Pinus Pengger",
      "Pusat Oleh-oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "247.000",
    image: "https://images.unsplash.com/photo-1559126137-3485b7427625?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Imogiri",
    duration: "1 Hari",
    location: "Yogyakarta",
    short_description: "Rasakan suasana magis Imogiri dan keindahan senja di Pantai Parangtritis.",
    destinations: [
      "Taman Sari",
      "Hutan Pinus",
      "Pantai Parangtritis",
      "Obelix Sea View",
      "Pusat Oleh-oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "228.000",
    image: "https://images.unsplash.com/photo-1570162872928-08f6756a402c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Gunung Kidul",
    duration: "1 Hari",
    location: "Yogyakarta",
    short_description: "Petualangan seru di Goa Pindul dan menikmati keindahan pantai-pantai Gunung Kidul.",
    destinations: [
      "Cave Tubing Goa Pindul",
      "Puncak Segoro",
      "Pantai Ngobaran",
      "Malioboro",
      "Pusat Oleh-oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "258.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Kulon Progo",
    duration: "1 Hari",
    location: "Yogyakarta",
    short_description: "Menikmati keindahan alam Kulon Progo dari Tumpeng Menoreh hingga air terjun.",
    destinations: [
      "Tumpeng Menoreh",
      "Candi Borobudur",
      "Air Terjun Kedung Kayang",
      "Obelix Village",
      "Wisata Oleh Oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "288.000",
    image: "https://images.unsplash.com/photo-1559126137-3485b7427625?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];

export const twoDayPackages = [
  {
    name: "Paket Sewon",
    duration: "2 Hari 1 Malam",
    location: "Yogyakarta",
    short_description: "Kombinasi wisata budaya, alam, dan pemandangan laut yang menakjubkan.",
    destinations: [
      "Pasar Ngasem",
      "Tamansari",
      "Candi Prambanan",
      "Kebun Buah Mangunan",
      "Hutan Pinus",
      "Pantai Parangtritis",
      "Obellix Sea View",
      "Pusat Oleh-oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Hotel Bintang 3 (1 Malam)",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "747.000",
    image: "https://images.unsplash.com/photo-1570162872928-08f6756a402c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Gondomanan",
    duration: "2 Hari 1 Malam",
    location: "Yogyakarta",
    short_description: "Jelajahi kebun binatang, spot foto unik, dan wisata budaya dalam 2 hari.",
    destinations: [
      "Suraloka Zoo",
      "Bhumi Merapi",
      "Ibarbo Park",
      "Pasar Ngasem",
      "Candi Prambanan",
      "Tempo Gelato",
      "Pusat Oleh-oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Hotel Bintang 3 (1 Malam)",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "759.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Wonosari",
    duration: "2 Hari 1 Malam",
    location: "Yogyakarta",
    short_description: "Nikmati keindahan pantai-pantai eksotis Wonosari dan spot senja terbaik.",
    destinations: [
      "Heha Ocean View",
      "Pantai Watulawang",
      "Pinus Pengger",
      "Pasar Ngasem",
      "Keraton",
      "Tebing Breksi",
      "Candi Plaosan",
      "Pusat Oleh-oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Hotel Bintang 3 (1 Malam)",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "709.000",
    image: "https://images.unsplash.com/photo-1559126137-3485b7427625?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Krapyak",
    duration: "2 Hari 1 Malam",
    location: "Yogyakarta",
    short_description: "Petualangan 2 hari menjelajahi pantai-pantai indah dan pemandangan dari ketinggian.",
    destinations: [
      "Pantai Mesra",
      "Pantai Ngobaran",
      "Obelix Sea View",
      "Heha Sky View",
      "Tebing Breksi",
      "Candi Prambanan",
      "Pusat oleh-Oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Hotel Bintang 3 (1 Malam)",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "778.000",
    image: "https://images.unsplash.com/photo-1570162872928-08f6756a402c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Kotagede",
    duration: "2 Hari 1 Malam",
    location: "Yogyakarta",
    short_description: "Eksplorasi lengkap dari alam, pantai, hingga spot foto instagramable di Jogja.",
    destinations: [
      "Kebun Buah Mangunan",
      "Hutan Pinus",
      "Gumuk Pasir",
      "Pantai Parangtritis",
      "Obelix Sea View",
      "Pasar Ngasem",
      "Tamansari",
      "Studio Gamplong",
      "Mahaloka Paradise",
      "Pule Payung",
      "Pusat Oleh-oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Hotel Bintang 3 (1 Malam)",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "747.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Gamping",
    duration: "2 Hari 1 Malam",
    location: "Yogyakarta",
    short_description: "Dari wisata sejarah Borobudur hingga pemandangan modern di Obelix Hills.",
    destinations: [
      "Taman Sari",
      "Kopi Klothok",
      "Obelix Hills",
      "Tebing Breksi",
      "Malioboro",
      "Tumpeng Menoreh",
      "VW Safari",
      "Borobudur",
      "Pusat Oleh-oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Hotel Bintang 3 (1 Malam)",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "879.000",
    image: "https://images.unsplash.com/photo-1559126137-3485b7427625?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Gedongtengen",
    duration: "2 Hari 1 Malam",
    location: "Yogyakarta",
    short_description: "Kombinasi sempurna antara wisata alam, kuliner, dan spot foto kekinian.",
    destinations: [
      "Tumpeng Menoreh",
      "Studio Gamplong",
      "Mahaloka Paradise",
      "Tempo Gelato",
      "Heha Sky View",
      "Pantai Mesra",
      "Pantai Drini",
      "Pusat Oleh-oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Hotel Bintang 3 (1 Malam)",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "829.000",
    image: "https://images.unsplash.com/photo-1570162872928-08f6756a402c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Pundong",
    duration: "2 Hari 1 Malam",
    location: "Yogyakarta",
    short_description: "Petualangan lengkap dari Candi Borobudur, Lava Tour Merapi, hingga Goa Pindul.",
    destinations: [
      "Borobudur",
      "Air Terjun Kedung Kayang",
      "Lava Tour Merapi",
      "Kopi Klothok",
      "Goa Pindul",
      "Pantai Ngobaran",
      "Puncak Segoro",
      "Wisata Oleh Oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Hotel Bintang 3 (1 Malam)",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "877.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Paket Mantrijeron",
    duration: "2 Hari 1 Malam",
    location: "Yogyakarta",
    short_description: "Jelajahi pusat kota Jogja, nikmati kuliner, dan temukan spot foto terbaik.",
    destinations: [
      "Pasar Ngasem",
      "Keraton",
      "Puncak Becici",
      "Malioboro",
      "Hutan Pinus",
      "Tempo Gelato",
      "Obelix Hills",
      "Tebing Breksi",
      "Pusat oleh-oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Hotel Bintang 3 (1 Malam)",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "699.000",
    image: "https://images.unsplash.com/photo-1559126137-3485b7427625?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];

export const threeDayPackages = [
  {
    name: "Jogokaryan",
    duration: "3 Hari 2 Malam",
    location: "Yogyakarta",
    short_description: "Eksplorasi Jogja super lengkap dari wisata alam, budaya, sejarah, hingga kuliner.",
    destinations: [
      "Kopi Klothok",
      "Museum Merapi",
      "Candi Plaosan",
      "Tebing Breksi",
      "Hutan Pinus Asri",
      "Songgo Langit",
      "Pantai Parangtritis",
      "Malioboro",
      "Pasar Ngasem",
      "Tamansari",
      "Studio Gamplong",
      "Pusat Oleh Oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Hotel Bintang 3 (2 Malam)",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "1.027.000",
    image: "https://images.unsplash.com/photo-1570162872928-08f6756a402c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Mangkuyudan",
    duration: "3 Hari 2 Malam",
    location: "Yogyakarta",
    short_description: "Petualangan 3 hari menyusuri pantai, alam, dan spot-spot foto paling hits di Jogja.",
    destinations: [
      "Cave Tubing Goa Pindul",
      "Pantai Drini",
      "Obelix Sea View",
      "Pule Payung",
      "Sungai Mudal",
      "Studio Gamplong",
      "Malioboro",
      "Pasar Ngasem",
      "Tamansari",
      "Hutan Pinus Asri",
      "Heha SkyView",
      "Wisata Oleh Oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Hotel Bintang 3 (2 Malam)",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "1.125.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Kaliurang",
    duration: "3 Hari 2 Malam",
    location: "Yogyakarta",
    short_description: "Nikmati sunrise, jelajahi candi, dan rasakan suasana romantis di berbagai destinasi.",
    destinations: [
      "Candi Prambanan",
      "Tebing Breksi",
      "Obelix Hills",
      "Sunrise Mangunan",
      "Hutan Pinus Asri",
      "Gumuk Pasir",
      "Pantai Parangtritis",
      "Pasar Ngasem",
      "Tamansari",
      "Keraton",
      "Malioboro",
      "Wisata Oleh Oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Hotel Bintang 3 (2 Malam)",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "1.125.000",
    image: "https://images.unsplash.com/photo-1559126137-3485b7427625?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Danurejan",
    duration: "3 Hari 2 Malam",
    location: "Yogyakarta",
    short_description: "Paket terlengkap untuk merasakan semua pesona Jogja, dari gunung hingga pantai.",
    destinations: [
      "Kopi klothok",
      "Lava tour Merapi",
      "Borobudur",
      "Malioboro",
      "Pantai Indrayanti",
      "Pantai Drini",
      "Heha Sky View",
      "Pinus Pengger",
      "Pasar Ngasem",
      "Tamansari",
      "Jurang Kanigoro",
      "Wisata Oleh Oleh",
    ],
    includes: [
      "Mobil + Driver + BBM",
      "Hotel Bintang 3 (2 Malam)",
      "Tiket Masuk Wisata",
      "Air Mineral",
      "Parkir",
    ],
    excludes: ["Makan", "Pengeluaran Pribadi"],
    price: "1.194.000",
    image: "https://images.unsplash.com/photo-1570162872928-08f6756a402c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];

export const companyPackages = [
  {
    name: "Paket Adventure",
    duration: "2 Hari 1 Malam",
    location: "Yogyakarta",
    short_description: "Dirancang khusus untuk kegiatan outing perusahaan dengan aktivitas outbound dan gala dinner.",
    destinations: [
      "Outbound",
      "Cave Tubing Goa Pindul",
      "Heha Sky View",
      "Gala Dinner",
      "Pantai Parangtritis",
      "Jeep Gumuk Pasir",
      "Obelix Sea View",
      "Pusat Oleh Oleh",
    ],
    includes: [
      "Bus Pariwisata",
      "Hotel Bintang 3 (1 Malam)",
      "Makan 4x",
      "Dokumentasi",
      "Tour Leader",
      "Spanduk & Kaos",
    ],
    excludes: ["Pengeluaran Pribadi"],
    price: "1.677.000",
    image: "https://images.unsplash.com/photo-1593719592254-69d2357c145e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];
